version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
    depends_on:
      - mysql
  php:
    image: php:7.4-fpm
    volumes:
      - ./:/app
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
